# OpenCV Workshop


In [1]:
import cv2
import numpy as np

## Let's start

In [2]:
# Basic implementation
img = cv2.imread("messi5.jpg") # img is a numpy array here

cv2.imshow('image', img)

print("Shape = {}".format(img.shape)) #Gives the shape of the image
print(img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

Shape = (342, 548, 3)
[[[ 39  43  44]
  [ 42  46  47]
  [ 44  47  52]
  ...
  [ 57  55  55]
  [ 55  53  53]
  [ 52  50  50]]

 [[ 37  40  44]
  [ 42  45  49]
  [ 46  49  54]
  ...
  [ 62  60  60]
  [ 60  58  58]
  [ 57  55  55]]

 [[ 41  45  50]
  [ 46  50  55]
  [ 51  55  60]
  ...
  [ 64  63  65]
  [ 63  62  64]
  [ 60  59  61]]

 ...

 [[ 56 143  99]
  [ 48 133  89]
  [ 49 129  86]
  ...
  [ 60 134  92]
  [ 63 134  94]
  [ 73 145 103]]

 [[ 54 138  96]
  [ 59 141  99]
  [ 50 130  87]
  ...
  [ 56 132  91]
  [ 69 142 104]
  [ 64 137  97]]

 [[ 45 129  87]
  [ 58 140  98]
  [ 71 151 108]
  ...
  [ 49 124  86]
  [ 52 125  87]
  [ 51 124  86]]]


##  Reading with various flags & Saving

In [3]:
img = cv2.imread("messi5.jpg") # same as cv2.imread("messi.jpg", 1)
img_gray = cv2.imread("messi5.jpg", 0) # Grayscale
img_unchanged = cv2.imread("messi5.jpg", -1) # Unchanged

cv2.imshow('image', img)
cv2.imshow('gray', img_gray)
cv2.imshow('unchanged', img_unchanged)

print("Shape = {}".format(img_gray.shape)) #Gives the shape of the gray imege 3 not present
print(img_gray)

cv2.imwrite("gray_messi.jpg", img_gray)

cv2.waitKey(0) 
cv2.destroyAllWindows()

Shape = (342, 548)
[[ 43  46  48 ...  55  53  50]
 [ 41  46  50 ...  60  58  55]
 [ 46  51  56 ...  64  63  60]
 ...
 [120 110 107 ... 113 114 124]
 [116 119 108 ... 111 122 117]
 [107 118 129 ... 104 105 104]]


## Resizing and cropping

In [4]:
img = cv2.imread("messi5.jpg")

# Resize
new_x = 300
new_y = 300
img_resize = cv2.resize(img, (new_x, new_y)) #to a given size

# Rescale
img_rescale = cv2.resize(img, (0, 0), fx = 0.5, fy = 0.5) #to a given scale

# Crop
cropped_img = img[10:300, 120:400]

cv2.imshow('image', img)
cv2.imshow('resize', img_resize)
cv2.imshow('rescale', img_rescale)

cv2.imshow("Cropped", cropped_img)

cv2.waitKey(0) 
cv2.destroyAllWindows()

## Changing colorspaces

In [5]:
img = cv2.imread("messi5.jpg")

img1 = img.copy()
gray_img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2 = img.copy()
rgb_img = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
img3 = img.copy()
hsv_img = cv2.cvtColor(img3, cv2.cv2.COLOR_BGR2HSV)

cv2.imshow('image', img)
cv2.imshow('gray image', gray_img)
cv2.imshow('rgb image', rgb_img)
cv2.imshow('hsv image', hsv_img)

cv2.waitKey(0) 
cv2.destroyAllWindows()

## Thresholding
### Simple Thresholding

In [6]:
img = cv2.imread("sudoku.png")

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_,threshold=cv2.threshold(gray_img,127,255,cv2.THRESH_BINARY)
_,binary_inv=cv2.threshold(gray_img,127,255,cv2.THRESH_BINARY_INV)
_,turnc=cv2.threshold(gray_img,127,255,cv2.THRESH_TRUNC)
_,tozero=cv2.threshold(gray_img,127,255,cv2.THRESH_TOZERO)
_,tozero_inv=cv2.threshold(gray_img,127,255,cv2.THRESH_TOZERO_INV)

cv2.imshow('image', img)
cv2.imshow('threshold binary', threshold)
cv2.imshow('threshold binary inv', binary_inv)
cv2.imshow('threshold trunc', turnc)
cv2.imshow('threshold tozero', tozero)
cv2.imshow('threshold tozero inv', tozero_inv)

cv2.waitKey(0) 
cv2.destroyAllWindows()

### Adaptive thresholding

In [7]:
img = cv2.imread("sudoku.png")

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_,threshold=cv2.threshold(gray_img,127,255,cv2.THRESH_BINARY)

thresh1 = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 199, 5)
thresh2 = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 199, 5)

cv2.imshow('image', img)
cv2.imshow('global', threshold)
cv2.imshow('mean', thresh1)
cv2.imshow('gaussian', thresh2)

cv2.waitKey(0) 
cv2.destroyAllWindows()

## Masking

In [8]:
img = cv2.imread("cheems.png")

#converting the image to hsv
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# masking
lower_yellow = np.array([22, 93, 0]) #[hue, saturation, brightness]
upper_yellow = np.array([45, 255, 255])

lower_red = np.array([0,50,50])
upper_red = np.array([10,255,255])

masked_image = cv2.inRange(img_hsv, lower_red, upper_red)

cv2.imshow('image', img)
# cv2.imshow('hsv', img_hsv)
cv2.imshow('masked', masked_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Morphological operations

In [9]:
img = cv2.imread("LinuxLogo.jpg")
# img = cv2.imread("b&w1.png")

# Erosion
kernel = np.ones((10,10),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

# Dilation
dilation = cv2.dilate(img,kernel,iterations = 1)

cv2.imshow('image', img)
cv2.imshow('eroded', erosion)
cv2.imshow('dilated', dilation)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Drawing on images

In [10]:
img = np.zeros([512,512, 3], np.uint8) #create a blank image
# print(img)
# cv2.line(image, start_point, end_point, color, thickness)
img = cv2.line(img, (0,0),(255,255), (100, 255, 0), 1)


#cv2.rectangle(image, start_point, end_point, color, thickness)
img = cv2.rectangle(img, (300,30), (500,128), (0, 0, 255), 10)

#cv2.circle(image, center_coordinates, radius, color, thickness)
img = cv2.circle(img, (400,300), 80, (0, 100, 200), 5)


font = cv2.FONT_HERSHEY_TRIPLEX
#cv2.circle(image, center_coordinates, radius, color, thickness)
img= cv2.putText(img, 'OpenCV', (20, 400), font, 2, (255,992,400))


cv2.imshow('image', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Countours
### Contours based on colour

In [11]:
img = cv2.imread("colourful_shapes.jpg")
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower_yellow = np.array([22, 150, 140]) #[hue, saturation, brightness]
upper_yellow = np.array([45, 255, 255])

masked_image = cv2.inRange(img_hsv, lower_yellow, upper_yellow)

cv2.imshow('image', img)
cv2.imshow('masked', masked_image)

contours, hierarchy = cv2.findContours(masked_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print(contours)

# All contours together
img1 = img.copy()
cv2.drawContours(img1, contours, -1, (0, 255, 0), 3)
cv2.imshow('image with contours', img1)

# Draw indivudal contours
img2 = img.copy()
cv2.drawContours(img2, contours, 0, (0, 255, 0), 3)
cv2.imshow('indivudal contour', img2)


cv2.waitKey(0)
cv2.destroyAllWindows()

(array([[[506, 300]],

       [[505, 301]],

       [[504, 301]],

       ...,

       [[509, 301]],

       [[508, 300]],

       [[507, 300]]], dtype=int32), array([[[189, 166]],

       [[189, 167]],

       [[190, 168]],

       [[190, 169]],

       [[190, 170]],

       [[190, 171]],

       [[190, 172]],

       [[190, 173]],

       [[190, 174]],

       [[191, 175]],

       [[191, 176]],

       [[191, 177]],

       [[191, 178]],

       [[191, 179]],

       [[192, 180]],

       [[192, 181]],

       [[192, 182]],

       [[192, 183]],

       [[192, 184]],

       [[192, 185]],

       [[192, 186]],

       [[193, 187]],

       [[193, 188]],

       [[193, 189]],

       [[193, 190]],

       [[193, 191]],

       [[194, 192]],

       [[194, 193]],

       [[194, 194]],

       [[194, 195]],

       [[194, 196]],

       [[194, 197]],

       [[194, 198]],

       [[195, 199]],

       [[195, 200]],

       [[195, 201]],

       [[195, 202]],

       [[196, 203]],

    

# To find the largest contour - Another example

In [12]:
img = cv2.imread("blobs_binary.png")
print(img.shape)
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray_img.shape)
cv2.imshow('gray', gray_image)

contours, hierarchy = cv2.findContours(gray_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
# print(contours)

# All contours together
img1 = img.copy()
cv2.drawContours(img1, contours, -1, (0, 255, 0), 1)
cv2.imshow('image with contours', img1)

# Largest contour
# biggest_contour = max(contours, key = cv2.contourArea)
# cv2.drawContours(img1, biggest_contour, -1, (255, 255, 0), 2)
# cv2.imshow('largest contour', img1)

cv2.waitKey(0)
cv2.destroyAllWindows()

(254, 256, 3)
(563, 558)


### Image Moments using contour
Image moments are weighted average of pixel intensites in the image, they help to calculate some features like the center of mass of the object, area of the object etc. We can get the image moment of this contour using the function cv2.moments() which gives us a dictonary of various properties to use. 

In [13]:
img = cv2.imread("colourful_shapes.jpg")
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower_yellow = np.array([22, 150, 140]) #[hue, saturation, brightness]
upper_yellow = np.array([45, 255, 255])

masked_image = cv2.inRange(img_hsv, lower_yellow, upper_yellow)

# cv2.imshow('image', img)
# cv2.imshow('masked', masked_image)

contours, hierarchy = cv2.findContours(masked_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

img1 = img.copy()
cv2.drawContours(img1, contours[1], -1, (0, 255, 0), 3)


# Find the moments
cnt = contours[1]
M = cv2.moments(cnt)
print(M)

# Find the centroid
# x - coordinate of centroid
cx = int(M['m10']/M['m00'])
# y - coordinate of the centroid
cy = int(M['m01']/M['m00'])

# print('Centroid: ({}, {})'.format(cx, cy))
cv2.circle(img1, (cx, cy), 5, (0, 0, 255), -1)

area = cv2.contourArea(contours[1])
print("Area = {}".format(area))

# perimeter = cv2.arcLength(contours[1], True)
# print("Perimeter = {}".format(perimeter))

cv2.imshow('image with contours', img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

{'m00': 6708.0, 'm10': 1533272.0, 'm01': 1472210.6666666665, 'm20': 354677649.3333333, 'm11': 336507698.8333333, 'm02': 327316948.6666666, 'm30': 82995657905.20001, 'm21': 77840984366.9, 'm12': 74815835385.9, 'm03': 73684297235.2, 'mu20': 4212081.95348835, 'mu11': -857.1149870753288, 'mu02': 4209577.311998963, 'mu30': 153523.77536010742, 'mu21': -39812.58298289776, 'mu12': 184102.5988278389, 'mu03': -983.2880859375, 'nu20': 0.09360751252539153, 'nu11': -1.90481578407818e-05, 'nu02': 0.09355185044137268, 'nu30': 4.1657481192924974e-05, 'nu21': -1.0802834433700236e-05, 'nu12': 4.9954806871119564e-05, 'nu03': -2.6680756678298995e-07}
Area = 6708.0


### Bounding and min area rectangles

In [14]:
img = cv2.imread("rubiks.png")
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower_yellow = np.array([22, 150, 140]) #[hue, saturation, brightness]
upper_yellow = np.array([45, 255, 255])

masked_image = cv2.inRange(img_hsv, lower_yellow, upper_yellow)

# cv2.imshow('image', img)
# cv2.imshow('masked', masked_image)

contours, hierarchy = cv2.findContours(masked_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

# img1 = img.copy()
cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

# Drawing a bounding rectangle
cnt = contours[2]
x, y, w, h = cv2.boundingRect(cnt)
img = cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 255), 2)

# Drawing a min area rectangle
rect = cv2.minAreaRect(cnt)
box = cv2.boxPoints(rect)
box = np.int0(box)
img = cv2.drawContours(img, [box], 0, (0,0,255), 2)

cv2.imshow('image with contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Contour Approximation

In [15]:
img = cv2.imread("rubiks.png")
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower_yellow = np.array([22, 150, 140]) #[hue, saturation, brightness]
upper_yellow = np.array([45, 255, 255])

masked_image = cv2.inRange(img_hsv, lower_yellow, upper_yellow)

# cv2.imshow('image', img)
# cv2.imshow('masked', masked_image)

contours, hierarchy = cv2.findContours(masked_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
img1 = img.copy()

cv2.drawContours(img1, contours[1], -1, (0, 255, 0), 3)

epsilon = 0.2 * cv2. arcLength(contours[1], True)
approx = cv2.approxPolyDP(contours[1], epsilon, True)

img2 = img.copy()
cv2.drawContours(img2, [approx], -1, (0, 255, 255), 3)

cv2.imshow('image with contours', img1)
cv2.imshow('approximated contours', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Task

In [16]:
# Load the image
img = cv2.imread("colourful_shapes.jpg")
# Convert to greyscale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Convert to binary image by thresholding
_, threshold = cv2.threshold(img_gray, 245, 255, cv2.THRESH_BINARY_INV)
# Find the contours
contours, _ = cv2.findContours(threshold, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# For each contour approximate the curve and
# detect the shapes.
for cnt in contours:
    epsilon = 0.01*cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)
    cv2.drawContours(img, [approx], 0, (0), 3)
    # Position for writing text
    x,y = approx[0][0]
 
    if len(approx) == 3:
        cv2.putText(img, "Triangle", (x, y), cv2.FONT_HERSHEY_COMPLEX, 1, 0,2)
    elif len(approx) == 4:
        cv2.putText(img, "Rectangle", (x, y), cv2.FONT_HERSHEY_COMPLEX, 1, 0,2)
    elif len(approx) == 5:
        cv2.putText(img, "Pentagon", (x, y), cv2.FONT_HERSHEY_COMPLEX, 1, 0,2)
    elif 6 < len(approx) < 15:
        cv2.putText(img, "Ellipse", (x, y), cv2.FONT_HERSHEY_COMPLEX, 1, 0,2)
    else:
        cv2.putText(img, "Circle", (x, y), cv2.FONT_HERSHEY_COMPLEX, 1, 0,2)
cv2.imshow("final", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Video Processing 

In [17]:
#read the video
cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret,frame = cap.read()
    if(ret == False):
        break
        
    frame = cv2.resize(frame, (640, 640))
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    thresh =  cv2.adaptiveThreshold(frame_gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 15, 10)
    
    cv2.imshow("video", frame)
    cv2.imshow("video_gray", frame_gray)
    cv2.imshow("thresh", thresh)
    
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

## Resources

Youtube playlist(ProgrammingKnowldge) :  https://youtube.com/playlist?list=PLS1QulWo1RIa7D1O6skqDQ-JZ1GGHKK-K

Numpy documentation : https://numpy.org/doc/stable/reference/

RGB & HSV data : https://www.rapidtables.com/web/color/RGB_Color.html#:~:text=RGB%20color%20space%20or%20RGB,*256%3D16777216%20possible%20colors.

OpenCV documentation : https://docs.opencv.org/4.x/

Thresholding : https://docs.opencv.org/4.x/d7/d4d/tutorial_py_thresholding.html

Morphological operations : https://docs.opencv.org/3.4/d9/d61/tutorial_py_morphological_ops.html

Drawing Functions : https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html

Contours : https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html

Contour_retrival modes : https://docs.opencv.org/4.x/d9/d8b/tutorial_py_contours_hierarchy.html

Image moments(wiki) : https://en.wikipedia.org/wiki/Image_moment

Image moments(openCV doc): https://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html

In [18]:
from IPython.display import Image
Image(url='sponge.gif')  

In [19]:
from IPython.display import Image
Image(url='200.gif') 